server:
  port: 8088
##########################################
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/food?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 1
    host: localhost
    port: 6379
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update  # 第一次建表create  后面用update，要不然每次重启都会新建表
    show-sql: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
##########################################
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.imooc.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #用于在控制台sql打印的
##########################################
mapper:
  mappers:com:
    imooc:
    mapper:
    MyMapper:
  not-empty: false

  identity: MYSQL
pagehelper:
  support-methods-arguments: true